# Decision Tree


## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Importing the dataset

In [3]:
dataset = pd.read_csv('_crop+yield+prediction_data_crop_yield.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset

Crop  ...  Yield
0       Cocoa, beans  ...  11560
1       Cocoa, beans  ...  11253
2       Cocoa, beans  ...   9456
3       Cocoa, beans  ...   9321
4       Cocoa, beans  ...   8800
..               ...  ...    ...
151  Rubber, natural  ...   6721
152  Rubber, natural  ...   6248
153  Rubber, natural  ...   6842
154  Rubber, natural  ...   5571
155  Rubber, natural  ...   5903

[156 rows x 6 columns]

In [5]:
dataset.dtypes

Crop                                     object
Precipitation (mm day-1)                float64
Specific Humidity at 2 Meters (g/kg)    float64
Relative Humidity at 2 Meters (%)       float64
Temperature at 2 Meters (C)             float64
Yield                                     int64
dtype: object

In [6]:
dataset.describe()

Precipitation (mm day-1)  ...          Yield
count                156.000000  ...     156.000000
mean                2486.498974  ...   56153.096154
std                  289.457914  ...   70421.958897
min                 1934.620000  ...    5249.000000
25%                 2302.990000  ...    8327.750000
50%                 2424.550000  ...   18871.000000
75%                 2718.080000  ...   67518.750000
max                 3085.790000  ...  203399.000000

[8 rows x 5 columns]

In [7]:
X

array([['Cocoa, beans', 2248.92, 17.72, 83.4, 26.01],
       ['Cocoa, beans', 1938.42, 17.54, 82.11, 26.11],
       ['Cocoa, beans', 2301.54, 17.81, 82.79, 26.24],
       ['Cocoa, beans', 2592.35, 17.61, 85.07, 25.56],
       ['Cocoa, beans', 2344.72, 17.61, 84.12, 25.76],
       ['Cocoa, beans', 2339.3, 17.7, 84.54, 25.76],
       ['Cocoa, beans', 2326.09, 18.09, 84.63, 26.11],
       ['Cocoa, beans', 2718.08, 18.3, 85.43, 26.12],
       ['Cocoa, beans', 2061.61, 17.8, 84.36, 25.88],
       ['Cocoa, beans', 1934.62, 17.94, 83.43, 26.21],
       ['Cocoa, beans', 2217.12, 18.03, 84.39, 26.1],
       ['Cocoa, beans', 2249.7, 18.01, 84.24, 26.11],
       ['Cocoa, beans', 2530.96, 18.15, 85.33, 26.02],
       ['Cocoa, beans', 2504.7, 18.19, 85.45, 26.02],
       ['Cocoa, beans', 2686.2, 18.38, 85.77, 26.13],
       ['Cocoa, beans', 2414.79, 18.18, 85.76, 25.93],
       ['Cocoa, beans', 1999.53, 18.2, 84.36, 26.27],
       ['Cocoa, beans', 2362.8, 18.7, 84.03, 26.79],
       ['Cocoa, beans'

## Encoding categorical data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
X

array([[1.0, 0.0, 0.0, ..., 17.72, 83.4, 26.01],
       [1.0, 0.0, 0.0, ..., 17.54, 82.11, 26.11],
       [1.0, 0.0, 0.0, ..., 17.81, 82.79, 26.24],
       ...,
       [0.0, 0.0, 0.0, ..., 18.67, 85.48, 26.46],
       [0.0, 0.0, 0.0, ..., 18.5, 84.85, 26.43],
       [0.0, 0.0, 0.0, ..., 18.51, 83.52, 26.72]], dtype=object)

## Feature Scaling

In [10]:
y = y.reshape(-1,1)

In [11]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [13]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

## Predicting the Test set results

In [14]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-0.66 -0.62]
 [ 1.49  1.53]
 [-0.69 -0.66]
 [-0.34 -0.23]
 [-0.64 -0.68]
 [-0.66 -0.66]
 [ 1.35  1.57]
 [-0.39 -0.28]
 [-0.66 -0.71]
 [ 1.73  2.07]
 [-0.36 -0.37]
 [ 1.49  1.65]
 [-0.36 -0.27]
 [-0.67 -0.66]
 [ 1.64  1.23]
 [-0.65 -0.66]
 [-0.71 -0.69]
 [-0.67 -0.67]
 [ 1.81  1.62]
 [-0.7  -0.71]
 [-0.66 -0.68]
 [-0.68 -0.67]
 [-0.67 -0.69]
 [ 1.57  1.6 ]
 [-0.36 -0.37]
 [-0.64 -0.71]
 [-0.36 -0.44]
 [ 1.49  1.77]
 [-0.44 -0.42]
 [-0.34 -0.36]
 [-0.72 -0.69]
 [-0.68 -0.67]]


In [15]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[1.0, 0.0, 0.0, 0.0, 2729.53, 18.41, 86.03, 26.11]])))

array([9956.])

In [16]:
sc_y.inverse_transform(y_pred)

array([  9956., 160862.,   7663.,  32385.,  11108.,   9956., 151070.,
        28829.,  10010., 177543.,  30627., 160862.,  30627.,   9322.,
       171189.,  10737.,   6275.,   9322., 183004.,   6913.,  10058.,
         8604.,   8865., 166136.,  30627.,  11487.,  30627., 160862.,
        25187.,  32385.,   5765.,   8300.])

## Evaluating the model

In [17]:
y_test = y_test.reshape(-1,1)

In [18]:
y_pred = y_pred.reshape(-1,1)

### Mean Absolute Error (MAE)







In [19]:
from sklearn.metrics import mean_absolute_error
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 0.07770309513684688


### Mean Squared Error (MSE)

In [20]:
from sklearn.metrics import mean_squared_error
print("MSE",mean_squared_error(y_test,y_pred))

MSE 0.016410131096273546


### Root Mean Squared Error (RMSE)

In [21]:
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 0.12810203392715333


### Root Mean Squared Log Error (RMSLE)

In [22]:
print("RMSLE",np.log(np.sqrt(mean_squared_error(y_test,y_pred))))

RMSLE -2.054928192554027


### R Squared (R2)

In [23]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print(r2)

0.9824658285421994


### Adjusted R Squared

In [24]:
n=155
k=5
adj_r2_score = 1 - ((1-r2)*(n-1)/(n-k-1))
print(adj_r2_score)

0.981877433526837
